server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/inventory_db"
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  cloud:
    gcp:
      pubsub:
        emulator-host: "localhost:8085"
    stream:
      function:
        definition: draftOrderCreated
      bindings:
        draftOrderCreated-in-0:
          binder: pubsub
          destination: draftOrderCreated
          group: inventoryService
        draftOrderCreated-out-0:
          binder: pubsub
          destination: inventoryReserved
          group: userService
        inventoryReservationCancelled-out-0:
          binder: pubsub
          destination: inventoryReservationCancelled
          group: orderService
      source: inventoryReservationCancelled
