server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/inventory_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        reserveItemChannelOut:
          destination: reserveItemChannelOut
          group: Out
          producer:
            required-groups: Out
        reserveItemChannelIn:
          destination: reserveItemChannelIn
          group: In
