server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: "jdbc:mysql://localhost:3306/inventory_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: onOrderCreatedDraft;onInventoryReservationCancelledForOrder;onQuotaDeductionCancelledForOrder
    stream:
      poller:
        fixed-delay: 10
      bindings:
        onOrderCreatedDraft-in-0:
          binder: pubsub
          destination: orderCreatedDraft
          group: order
          consumer:
            concurrency: 4 # customize concurrency for inbound events stream processing
        onOrderCreatedDraft-out-0:
          destination: inventoryReservationCreatedForOrder
          binder: pubsub
          group: inventory
          producer:
            required-groups: inventory # create queue explicitly
        onInventoryReservationCancelledForOrder-out-0:
          binder: pubsub
          destination: inventoryReservationCancelledForOrder
          group: inventory
          producer:
            required-groups: inventory # create queue explicitly
        onQuotaDeductionCancelledForOrder-in-0:
          binder: pubsub
          destination: quotaDeductionCancelledForOrder
          group: quota

