server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/inventory_db"
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
