server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

app:
  inventory-service:
    url: "http://localhost:8081"
  user-service:
    url: "http://localhost:8083"
