server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  cloud:
    gcp:
      pubsub:
        emulator-host: "localhost:8085"
    function:
      definition: onInventoryReservationCancelledForOrder;onQuotaDeductedForOrder
    stream:
      poller:
        fixed-delay: 100
      bindings:
        onOrderCreatedDraft-out-0:
          binder: pubsub
          destination: orderCreatedDraft
          group: order
          producer:
            required-groups: order # create queue explicitly - for supplier
        onInventoryReservationCancelledForOrder-in-0:
          binder: pubsub
          destination: inventoryReservationCancelledForOrder
          group: inventory
        onQuotaDeductedForOrder-in-0:
          binder: pubsub
          destination: quotaDeductedForOrder
          group: quota # create durable queue
      source: onOrderCreatedDraft

app:
  inventory-service:
    url: "http://localhost:8081"
  user-service:
    url: "http://localhost:8083"
