server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled:
  cloud:
    gcp:
      pubsub:
        emulator-host: "localhost:8085"
    stream:
      function:
        definition: inventoryReservationCancelled
      bindings:
        draftOrderCreated-out-0:
          binder: pubsub
          destination: draftOrderCreated
          group: inventoryService
        inventoryReservationCancelled-in-0:
          binder: pubsub
          destination: inventoryReservationCancelled
          group: orderService
      source: draftOrderCreated

app:
  inventory-service:
    url: "http://localhost:8081"
  user-service:
    url: "http://localhost:8083"
