server:
  port: 8083

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: onInventoryReservationCreatedForOrder;onQuotaDeductionCancelledForOrder
    stream:
      bindings:
        onInventoryReservationCreatedForOrder-out-0:
          destination: quota-deducted-for-order
          group: quota
          binder: pubsub
        onInventoryReservationCreatedForOrder-in-0:
          destination: inventory-reservation-created-for-order
          group: inventory
          binder: pubsub
        onQuotaDeductionCancelledForOrder-out-0:
          destination: quota-deduction-cancelled-for-order
          group: quota
          binder: pubsub
