server:
  port: 8083

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        deductUserQuotaChannelOut:
          binder: rabbit
          destination: deductUserQuotaChannelOut
          group: Out
          producer:
            required-groups: Out
        deductUserQuotaChannelIn:
          binder: rabbit
          destination: deductUserQuotaChannelIn
          group: In
