server:
  port: 8083

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gcp:
      pubsub:
        emulator-host: "localhost:8085"
    function:
      definition: onInventoryReservationCreatedForOrder;onQuotaDeductionCancelledForOrder
    stream:
      bindings:
        onInventoryReservationCreatedForOrder-out-0:
          destination: quotaDeductedForOrder
          group: quota
          binder: pubsub
        onInventoryReservationCreatedForOrder-in-0:
          destination: inventoryReservationCreatedForOrder
          group: inventory
          binder: pubsub
        onQuotaDeductionCancelledForOrder-out-0:
          destination: quotaDeductionCancelledForOrder
          group: quota
          binder: pubsub
