server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/user_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sleuth:
    sampler:
      probability: 1
  cloud:
    function:
      definition: onInventoryReservationCreatedForOrder;onQuotaDeductionCancelledForOrder
    stream:
      poller:
        fixed-delay: 10
      bindings:
        onInventoryReservationCreatedForOrder-in-0:
          destination: inventoryReservationCreatedForOrder
          group: inventory
          binder: pubsub
        onInventoryReservationCreatedForOrder-out-0:
          destination: quotaDeductedForOrder
          group: quota
          binder: pubsub
        onQuotaDeductionCancelledForOrder-out-0:
          destination: quotaDeductionCancelledForOrder
          group: quota
          binder: pubsub
